Repository softeerbootcamp-6th/Team6-6CanDoIt, pull requests merged in 2025-08, with the labels that each got.

#22 🎨 - Icon viewBox width와 height연동
  frontend/src/components/atoms/Icon/Icons.tsx
Labels: 🚨 HotFix

#28 ✨ Feature: 각 모듈 별 테스트 기본 구조 설정
  backend/application-modules/api-server/build.gradle
  backend/application-modules/api-server/src/test/resources/application.yml
  backend/application-modules/batch-server/build.gradle
  backend/application-modules/batch-server/src/test/resources/application.yml
  backend/application-modules/build.gradle
  backend/build.gradle
  backend/domain-modules/build.gradle
  backend/domain-modules/image-domain/build.gradle
  backend/domain-modules/image-domain/src/test/resources/application.yml
  backend/settings.gradle
Labels: ⚙️ Setting, ✅ Test

#24 ✨ Feature: Backend CI workflow 동작 파일 추가
  .github/workflows/BE-CI.yml
Labels: ⚙️ Setting, ✨ Feature

#32 ✨ Feature : atoms에 Text, Heading 생성 및 icon 개선, molecules weatherIndex 생성
  frontend/src/assets/iconPath.ts
  frontend/src/components/atoms/Heading/Heading.tsx
  frontend/src/components/atoms/Icon/Icon.module.scss
  frontend/src/components/atoms/Icon/Icons.tsx
  frontend/src/components/atoms/Temperature/Temperature.tsx
  frontend/src/components/atoms/Text/Text.tsx
  frontend/src/components/atoms/ToggleButton/ToggleButton.module.scss
  frontend/src/components/atoms/ToggleButton/ToggleButton.tsx
  frontend/src/components/molecules/TextWithIcon/TextWithIcon.tsx
  frontend/src/components/molecules/WeatherCell/WeatherCell.tsx
  frontend/src/components/molecules/WeatherIndex/WeatherIndex.module.scss
  frontend/src/components/molecules/WeatherIndex/WeatherIndex.tsx
  frontend/src/components/organisms/TimeSeletor/TimeSeletor.module.scss
  frontend/src/components/organisms/TimeSeletor/TimeSeletor.tsx
  frontend/src/components/organisms/WeatherCard/WeatherCard.tsx
Labels: ✨ Feature, 🎨 Html&css

#37 [BE] - ✨ Feature: 예보 및 그리드 엔티티 및 도메인 추가
  backend/application-modules/api-server/src/test/java/com/softeer/ApiServerApplicationTests.java
  backend/application-modules/api-server/src/test/java/com/softeer/api/ApiServerApplicationTests.java
  backend/application-modules/batch-server/build.gradle
  backend/application-modules/batch-server/src/test/java/com/softeer/BatchServerApplicationTests.java
  backend/application-modules/batch-server/src/test/java/com/softeer/batch/BatchServerApplicationTests.java
  backend/build.gradle
  backend/domain-modules/forecast-domain/build.gradle
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Displayable.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/HumidityCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/PrecipitationCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/SkyCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/TemperatureCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/WindCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/DailyTemperatureEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ForecastEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ShortForecastDetailEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/ForecastType.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/PrecipitationType.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/Sky.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/WindDirection.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/ForecastAdapter.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastJdbcRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastJpaRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForestAdapterImpl.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ShortForecastDetailJpaRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/ForecastTestApplication.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/HumidityConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/PrecipitationConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/SkyConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/TemperatureConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/WindConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastJdbcRepositoryTest.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/ForecastFixture.java
  backend/domain-modules/grid-domain/build.gradle
  backend/domain-modules/grid-domain/src/main/java/com/softeer/domain/Grid.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/entity/GridEntity.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/repository/GridJpaRepository.java
  backend/domain-modules/grid-domain/src/main/resources/application.yml
  backend/domain-modules/grid-domain/src/test/java/com/softeer/GridTestApplication.java
  backend/domain-modules/grid-domain/src/test/java/com/softeer/domain/GridTest.java
  backend/domain-modules/grid-domain/src/test/java/com/softeer/repository/GridRepositoryTest.java
  backend/domain-modules/grid-domain/src/testFixtures/java/com/softeer/domain/GridFixture.java
  backend/domain-modules/image-domain/src/test/resources/application.yml
Labels: ⚙️ Setting, ✨ Feature, ✅ Test

#48 [BE] - ✨ Feature: 예보 엔티티 수정 및 일교차 도메인 구현
  backend/domain-modules/forecast-domain/build.gradle
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/DailyTemperature.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/DailyTemperatureEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ShortForecastDetailEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastJdbcRepository.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/DailyTemperatureTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastJdbcRepositoryTest.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/DailyTemperatureFixture.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/ForecastFixture.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#50 [BE] - ✨ Feature: Exception 모듈 구현
  .gitignore
  README.md
  backend/common-modules/exception/build.gradle
  backend/common-modules/exception/src/main/java/com/softeer/error/CustomException.java
  backend/common-modules/exception/src/main/java/com/softeer/error/ExceptionCreator.java
  backend/common-modules/exception/src/main/java/com/softeer/error/ExceptionInterface.java
  backend/settings.gradle
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: ✨ Feature

#53 [BE] - ✨ Feature: HttpStatus 정의
  backend/common-modules/exception/src/main/java/com/softeer/error/CustomException.java
  backend/common-modules/exception/src/main/java/com/softeer/error/ExceptionInterface.java
  backend/common-modules/exception/src/main/java/com/softeer/error/HttpStatus.java
Labels: ✨ Feature, 🔨 Refactor

#31 [FE] - ✨ Feature: atoms에 버튼 추가 및 colors에 grey-opacity-white클래스 추가
  frontend/src/App.css
  frontend/src/components/atoms/Button/Button.module.scss
  frontend/src/components/atoms/Button/Button.tsx
  frontend/src/components/atoms/WeatherContent/WeatherContent.module.scss
  frontend/src/components/atoms/WeatherContent/WeatherContent.tsx
  frontend/src/components/molecules/MountainCard/MountainCard.module.scss
  frontend/src/components/molecules/MountainCard/MountainCard.tsx
  frontend/src/components/molecules/WeatherContent/WeatherContent.tsx
  frontend/src/components/organisms/MountainCard/MountainCard.module.scss
  frontend/src/components/organisms/MountainCard/MountainCard.tsx
  frontend/src/components/organisms/MountainCardContainer/MountainCardContainer.module.scss
  frontend/src/components/organisms/MountainCardContainer/MountainCardContainer.tsx
  frontend/src/components/organisms/SearchBar/SearchBar.tsx
  frontend/src/pages/MainPage/MainPage.module.scss
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/styles/colors.scss
Labels: ✨ Feature, 🎨 Html&css

#58 [FE] - :art: titleMedium 같이 묶여있던 fontWeight, fontSize를 분해해서 둠
  frontend/src/theme/theme.ts
Labels: 🎨 Html&css, 🚨 HotFix

#68 [BE] - ✨ Feature: Querydsl-Module 구현 및 세팅
  backend/domain-modules/build.gradle
  backend/domain-modules/settings.gradle
  backend/infrastructure-modules/build.gradle
  backend/infrastructure-modules/querydsl-module/build.gradle
  backend/infrastructure-modules/querydsl-module/src/main/java/com/softeer/QuerydslConfig.java
  backend/settings.gradle
Labels: ⚙️ Setting, ✨ Feature

#72 [BE] - ✨ Feature, Test:
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Course.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/mapper/CourseMapper.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CoursePlanJdbcRepository.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryIntegrationTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryTest.java
  backend/domain-modules/mountain-domain/src/test/resources/sql/course-plan-data.sql
  backend/domain-modules/mountain-domain/src/test/resources/sql/course-plan-schema.sql
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CourseFixture.java
Labels: ✨ Feature, ✅ Test

#76 [BE] - 🧪 Test: TestContainers-Module 세팅
  backend/build.gradle
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastJdbcRepositoryTest.java
  backend/domain-modules/grid-domain/src/test/java/com/softeer/repository/GridRepositoryTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryIntegrationTest.java
  backend/infrastructure-modules/testcontainers-module/build.gradle
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/TestcontainersConfiguration.java
  backend/settings.gradle
Labels: ⚙️ Setting, ✅ Test

#77 [FE] - 💎 Refactor: 기존의 메인페이지 UI들을 emotion css 적용 및 재정의한 atomic 단위에 맞게 수정
  frontend/src/components/atoms/Button/Button.module.scss
  frontend/src/components/atoms/Button/Button.tsx
  frontend/src/components/atoms/UlList/UlList.module.scss
  frontend/src/components/atoms/UlList/UlList.tsx
  frontend/src/components/molecules/Dropdown/Dropdown.module.scss
  frontend/src/components/molecules/Dropdown/Dropdown.tsx
  frontend/src/components/molecules/MountainCardHeader/MountainCardHeader.tsx
  frontend/src/components/molecules/MoutainCardFooter/MountainCardFooter.tsx
  frontend/src/components/molecules/MultiLocationTemperature/MultiLocationTemperature.tsx
  frontend/src/components/molecules/WeatherContent/WeatherContent.tsx
  frontend/src/components/organisms/MountainCard/MountainCard.module.scss
  frontend/src/components/organisms/MountainCard/MountainCard.tsx
  frontend/src/components/organisms/SearchBar/SearchBar.module.scss
  frontend/src/components/organisms/SearchBar/SearchBar.tsx
  frontend/src/pages/MainPage/MainPage.module.scss
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/utils/utils.ts
Labels: 🎨 Html&css, 🔨 Refactor

#81 [BE] - ✨ Feature: 예보 조회 쿼리 작성
  .DS_Store
  backend/.DS_Store
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/PrecipitationCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/DailyTemperatureEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ForecastEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ShortForecastDetailEntity.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/ForecastType.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/ForecastAdapter.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/DailyTemperatureJpaRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastJdbcRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastQuerydslRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForestAdapterImpl.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ShortForecastDetailJpaRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/DailyTemperatureTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/HumidityConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/PrecipitationConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/SkyConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/TemperatureConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/WindConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastQuerydslRepositoryTest.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/DailyTemperatureFixture.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/ForecastFixture.java
  backend/domain-modules/grid-domain/src/test/java/com/softeer/repository/GridRepositoryTest.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/TestcontainersConfiguration.java
Labels: ✨ Feature, ✅ Test

#78 [BE] - ✨ Feature: Time 유틸 모듈 관련 구현
  backend/common-modules/util/src/main/java/com/softeer/activity/HikingActivityCalculator.java
  backend/common-modules/util/src/main/java/com/softeer/time/ApiTime.java
  backend/common-modules/util/src/main/java/com/softeer/time/ApiTimeUtil.java
  backend/common-modules/util/src/main/java/com/softeer/time/HikingTime.java
  backend/common-modules/util/src/main/java/com/softeer/time/ShortTimePeriod.java
  backend/common-modules/util/src/main/java/com/softeer/time/TimeUtil.java
  backend/common-modules/util/src/test/java/com/softeer/time/ApiTimeUtilTest.java
  backend/common-modules/util/src/test/java/com/softeer/time/TimeUtilTest.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Course.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/entity/CourseEntity.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CoursePlanJdbcRepository.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/mapper/CourseMapperTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryTest.java
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CourseFixture.java
Labels: ✨ Feature, ✅ Test

#96 [FE] - ✨ Feature: 프론트 CI / CD 구축
  .github/workflows/FE-CI-CD.yml
Labels: ⚙️ Setting, ✨ Feature, 🌎 Deploy

#98 [BE] - ✨ Feature: 산악 멘트 추천 유틸 클래스 구현
  backend/common-modules/util/src/main/java/com/softeer/activity/factor/PrecipitationFactor.java
  backend/common-modules/util/src/main/java/com/softeer/condition/AbstractRange.java
  backend/common-modules/util/src/main/java/com/softeer/condition/CentimeterRange.java
  backend/common-modules/util/src/main/java/com/softeer/condition/Condition.java
  backend/common-modules/util/src/main/java/com/softeer/condition/MillimeterRange.java
  backend/common-modules/util/src/main/java/com/softeer/condition/Range.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/Comment.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/CommentProvider.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/MeasurementLevel.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/TotalLevel.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/TypeLevel.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/comment/PrecipitationComment.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/comment/SnowAccumulationComment.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/comment/TemperatureComment.java
  backend/common-modules/util/src/main/java/com/softeer/recommend/comment/WindSpeedComment.java
  backend/common-modules/util/src/test/java/com/softeer/recommend/CommentProviderTest.java
  backend/common-modules/util/src/test/java/com/softeer/recommend/comment/PrecipitationCommentTest.java
  backend/common-modules/util/src/test/java/com/softeer/recommend/comment/SnowAccumulationCommentTest.java
  backend/common-modules/util/src/test/java/com/softeer/recommend/comment/TemperatureCommentTest.java
  backend/common-modules/util/src/test/java/com/softeer/recommend/comment/WindSpeedCommentTest.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#101 [BE] - ✨ Feature: 예보 도메인 비즈니스 로직 구현
  backend/domain-modules/build.gradle
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/exception/ForecastException.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/ForecastAdapter.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastQuerydslRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForestAdapterImpl.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastQuerydslRepositoryTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/service/ForecastUseCaseTest.java
Labels: ✨ Feature, ✅ Test

#106 [BE] - ✨ Feature: 유저 도메인 JpaEntity 및 도메인 객체 생성
  backend/domain-modules/image-domain/src/main/java/com/softeer/domain/Image.java
  backend/domain-modules/image-domain/src/main/java/com/softeer/entity/ImageEntity.java
  backend/domain-modules/image-domain/src/main/java/com/softeer/repository/ImageJpaRepository.java
  backend/domain-modules/image-domain/src/testFixtures/java/com/softeer/domain/ImageFixture.java
  backend/domain-modules/user-domain/build.gradle
  backend/domain-modules/user-domain/src/main/java/com/softeer/domain/User.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/entity/Role.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/entity/UserEntity.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserJpaRepository.java
  backend/domain-modules/user-domain/src/testFixtures/java/com/softeer/domain/UserFixture.java
Labels: ✨ Feature

#108 [BE] - ✨ Feature: mountain-module 내부 도메인 레코드 필드 추가(grid)
  backend/domain-modules/mountain-domain/build.gradle
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Course.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Mountain.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/mapper/CourseMapper.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/mapper/MountainMapper.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CourseAdapterImpl.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CourseJdbcRepository.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CourseJpaRepository.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CoursePlanJdbcRepository.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/MountainAdapterImpl.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/MountainJpaRepository.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/mapper/CourseMapperTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/mapper/MountainMapperTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CourseAdapterImplTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CourseJdbcRepositoryIntegrationTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CourseJdbcRepositoryTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/CoursePlanJdbcRepositoryIntegrationTest.java
  backend/domain-modules/mountain-domain/src/test/java/com/softeer/repository/impl/MountainAdapterImplTest.java
  backend/domain-modules/mountain-domain/src/test/resources/sql/cleanup.sql
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CourseFixture.java
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/MountainFixture.java
Labels: ✨ Feature, ✅ Test

#118 [BE] - ✨ Feature: 체감 기온 계산 유틸 클래스 구현
  backend/common-modules/util/src/main/java/com/softeer/apparent/ApparentTemperatureCalculator.java
  backend/common-modules/util/src/main/java/com/softeer/time/ApiTimeUtil.java
  backend/common-modules/util/src/main/java/com/softeer/time/TimeUtil.java
  backend/common-modules/util/src/test/java/com/softeer/time/ApiTimeUtilTest.java
Labels: ✨ Feature, 🔨 Refactor

#121 [FE] - ✨ Feature: 회원가입 UI 컴포넌트 구현
  frontend/src/components/molecules/Register/RegisterHeader.tsx
  frontend/src/components/organisms/Form/RegisterForm.tsx
  frontend/src/components/organisms/Register/RegisterCheckBoxes.tsx
  frontend/src/components/templates/Login/RegisterTemplate.tsx
  frontend/src/pages/LoginPage/LoginPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#115 [FE] - ✨ Feature: 제보하기 페이지의 UI 컴포넌트들 구현
  frontend/src/components/atoms/DayButton/DayButton.tsx
  frontend/src/components/atoms/DigitInput/DigitInput.tsx
  frontend/src/components/atoms/LabelButton/LabelButton.tsx
  frontend/src/components/atoms/LabelTextBox/LabelTextBox.tsx
  frontend/src/components/atoms/ReportImage/ReportImage.tsx
  frontend/src/components/atoms/ReporterImage/ReporterImage.tsx
  frontend/src/components/atoms/Text/CommonText.tsx
  frontend/src/components/molecules/CardCommentEllipsis/CardCommentEllipsis.tsx
  frontend/src/components/molecules/ChipItem/ChipItem.tsx
  frontend/src/components/molecules/DayColumn/DayColumn.tsx
  frontend/src/components/molecules/DaySelector/DaySelector.tsx
  frontend/src/components/molecules/HeartStat/HeartStat.tsx
  frontend/src/components/molecules/LabelButtonsColumn/LabelButtonsColumn.tsx
  frontend/src/components/molecules/LabelList/LabelList.tsx
  frontend/src/components/molecules/MinutesAgo/MinutesAgo.tsx
  frontend/src/components/molecules/ModalContent/AlertModalContent.tsx
  frontend/src/components/molecules/ModalContent/FilterModalContent.tsx
  frontend/src/components/molecules/ModalContent/InProgressModalContent.tsx
  frontend/src/components/molecules/ModalFooter/ModalFooter.tsx
  frontend/src/components/molecules/ModalHeader/ModalHeader.tsx
  frontend/src/components/molecules/ModalHeaderButton/ModalHeaderButton.tsx
  frontend/src/components/molecules/ReportCardFooter/FrontCardFooter.tsx
  frontend/src/components/molecules/ReportCardHeader/BackReportCardHeader.tsx
  frontend/src/components/molecules/TimeInput/TimeInput.tsx
  frontend/src/components/molecules/TimeRow/TimeRow.tsx
  frontend/src/components/organisms/Modal/AlertModal.tsx
  frontend/src/components/organisms/Modal/BaseModal.tsx
  frontend/src/components/organisms/Modal/FilterModal.tsx
  frontend/src/components/organisms/Modal/InProgressModal.tsx
  frontend/src/components/organisms/ReportCard/BackReportCard.tsx
  frontend/src/components/organisms/ReportCard/FrontReportCard.tsx
  frontend/src/components/organisms/ReportCard/ReportCardWrapper.tsx
  frontend/src/components/organisms/SearchBar/SearchBar.tsx
  frontend/src/components/organisms/SearchSectionChipsRow/SearchSectionChipsRow.tsx
  frontend/src/components/templates/ReportPage/ReportCardContainer.tsx
  frontend/src/components/templates/ReportPage/SearchSection.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/ReportPage/ReportPage.tsx
  frontend/src/utils/utils.ts
Labels: ✨ Feature, 🎨 Html&css

#120 [BE] - ✨ Feature: Mountain 도메인 레코드 필드 추가 및 위도, 경도 변환 로직 구현
  backend/domain-modules/grid-domain/src/main/java/com/softeer/domain/Coordinate.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/domain/Grid.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/exception/GridException.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/repository/GridJpaRepository.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/service/GridConverter.java
  backend/domain-modules/grid-domain/src/main/java/com/softeer/service/GridUseCase.java
  backend/domain-modules/grid-domain/src/test/java/com/softeer/repository/GridRepositoryTest.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/domain/Mountain.java
  backend/domain-modules/mountain-domain/src/main/java/com/softeer/repository/impl/CoursePlanJdbcRepository.java
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/MountainFixture.java
Labels: ✨ Feature, ✅ Test

#124 [BE] - ✨ Feature: 카드 관련 API
  backend/application-modules/api-server/build.gradle
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/HourlyWeatherResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/CourseCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastCardDetail.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/WeatherMetric.java
  backend/application-modules/api-server/src/main/java/com/softeer/exception/ExceptionControllerAdvice.java
  backend/application-modules/api-server/src/main/java/com/softeer/exception/ExceptionResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
  backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
  backend/application-modules/build.gradle
  backend/application-modules/setting.gradle
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/Forecast.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/domain/condition/TemperatureCondition.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/domain/condition/TemperatureConditionTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/service/ForecastUseCaseTest.java
  backend/domain-modules/forecast-domain/src/testFixtures/java/com/softeer/domain/ForecastFixture.java
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/CoursePlanFixture.java
  backend/domain-modules/mountain-domain/src/testFixtures/java/com/softeer/domain/SunTimeFixture.java
Labels: ⚙️ Setting, ✨ Feature, ✅ Test

#126 [FE] - ✨ Feature: 제보하기 모달 UI 구현
  frontend/src/components/molecules/ImageInputField/ImageInputField.tsx
  frontend/src/components/molecules/ModalButton/ModalButton.tsx
  frontend/src/components/molecules/ModalContent/ReportModalContent.tsx
  frontend/src/components/molecules/ModalFooter/ModalFooter.tsx
  frontend/src/components/molecules/ModalHeader/ModalHeader.tsx
  frontend/src/components/molecules/ModalTextInputBox/ModalTextInputBox.tsx
  frontend/src/components/organisms/Modal/BaseModal.tsx
  frontend/src/components/organisms/Modal/ReportModal.tsx
Labels: ✨ Feature

#128 [BE] - ✨ Feature: 회원가입 및 로그인 API 구현
  backend/application-modules/api-server/build.gradle
  backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignInRequest.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignUpRequest.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/SignApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/SignController.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/JwtException.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserId.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserIdArgumentResolver.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtGenerator.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtProperties.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtResolver.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/Token.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/SignService.java
  backend/application-modules/api-server/src/main/resources/application.yml
  backend/application-modules/api-server/src/test/java/com/softeer/service/auth/JwtTest.java
  backend/common-modules/exception/src/main/java/com/softeer/error/HttpStatus.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/entity/UserEntity.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/exception/UserException.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserAdapter.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserAdapterImpl.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserJpaRepository.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/SignUseCase.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/LoginIdChecker.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/PasswordChecker.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/impl/SignUseCaseImpl.java
  backend/domain-modules/user-domain/src/test/java/com/softeer/repository/impl/UserJpaRepositoryTest.java
Labels: ✨ Feature, ✅ Test

#133 [BE] - ⚙️ Setting: application-prod.yml 파일 jwt secretKey 값 세팅
  backend/application-modules/api-server/src/main/resources/application-prod.yml
Labels: ⚙️ Setting

#134 [BE} - 🚀 Release: 회원가입 및 로그인 API 배포
  .github/workflows/BE-CD.yml
  backend/application-modules/api-server/build.gradle
  backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignInRequest.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/request/SignUpRequest.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/SignApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/SignController.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/JwtException.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserId.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/LoginUserIdArgumentResolver.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtGenerator.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtProperties.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/JwtResolver.java
  backend/application-modules/api-server/src/main/java/com/softeer/security/auth/Token.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/SignService.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
  backend/application-modules/api-server/src/main/resources/application-prod.yml
  backend/application-modules/api-server/src/main/resources/application.yml
  backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
  backend/application-modules/api-server/src/test/java/com/softeer/service/auth/JwtTest.java
  backend/common-modules/exception/src/main/java/com/softeer/error/HttpStatus.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/ForecastAdapter.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForecastQuerydslRepository.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/repository/impl/ForestAdapterImpl.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/ForecastUseCase.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/service/impl/ForecastUseCaseImpl.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/repository/impl/ForecastQuerydslRepositoryTest.java
  backend/domain-modules/forecast-domain/src/test/java/com/softeer/service/ForecastUseCaseTest.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/entity/UserEntity.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/exception/UserException.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserAdapter.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserAdapterImpl.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserJpaRepository.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/SignUseCase.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/LoginIdChecker.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/check/PasswordChecker.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/impl/SignUseCaseImpl.java
  backend/domain-modules/user-domain/src/test/java/com/softeer/repository/impl/UserJpaRepositoryTest.java
  backend/infrastructure-modules/querydsl-module/src/main/java/com/softeer/QuerydslConfig.java
Labels: 🌎 Deploy

#138 [FE] - ✨ Feature : 배포 상태 확인을 위해 작업 내역 공유
  frontend/src/components/templates/ForecastMain.tsx
  frontend/src/components/templates/Login/MyPageTemplate.tsx
  frontend/src/pages/ForecastPage/ForecastPage.tsx
  frontend/src/pages/LoginPage/MyPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#142 [FE] - 💎 Refactor: 폴더 구조 변경 후 삭제할 파일들 삭제
  frontend/src/components/atoms/Image/CircleImage.tsx
  frontend/src/components/atoms/ReportImage_delete/ReportImage.tsx
  frontend/src/components/molecules/Button/ChipButton.tsx
  frontend/src/components/molecules/DayColumn_delete/DayColumn.tsx
  frontend/src/components/molecules/MinutesAgo_delete/MinutesAgo.tsx
  frontend/src/components/molecules/Modal/InProgressModalContent.tsx
  frontend/src/components/molecules/ReportCard/BackReportCardHeader.tsx
  frontend/src/components/molecules/ReportCard/FrontCardFooter.tsx
  frontend/src/components/organisms/Report/FrontReportCard.tsx
  frontend/src/components/organisms/Report/HeartStat.tsx
  frontend/src/components/organisms/Report/InProgressModal.tsx
Labels: 🔨 Refactor

#152 [BE] - ✨ Feature: 단기 날씨 예보 조회 구현
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/common/AbstractKmaApiCaller.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/config/ForecastApiType.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/config/RestClientConfig.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/mountain/MountainForecastApiCaller.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/mountain/dto/MountainForecastApiRequest.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/AbstractShortForecastApiCaller.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/ShortForecastApiCaller.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/UltraForecastApiCaller.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/request/ShortForecastApiRequest.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastApiResponse.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastBody.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastHeader.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastItem.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastItems.java
  backend/infrastructure-modules/kma-adapter-module/src/main/java/com/softeer/shortterm/dto/response/ShortForecastResponsePayload.java
  backend/infrastructure-modules/kma-adapter-module/src/test/java/com/softeer/shortterm/dto/request/ShortForecastApiRequestTest.java
  backend/infrastructure-modules/kma-adapter-module/src/test/java/com/softeer/shortterm/dto/response/ShortForecastApiResponseTest.java
  backend/infrastructure-modules/kma-adapter-module/src/testFixtures/java/com/softeer/shortterm/ShortForecastApiRequestFixture.java
  backend/infrastructure-modules/kma-adapter-module/src/testFixtures/java/com/softeer/shortterm/ShortForecastApiResponseFixture.java
  backend/infrastructure-modules/kma-adapter-module/src/testFixtures/java/com/softeer/shortterm/ShortForecastHeaderFixture.java
  backend/infrastructure-modules/kma-adapter-module/src/testFixtures/java/com/softeer/shortterm/ShortForecastItemFixture.java
Labels: ✨ Feature

#155 [BE] - ✨ Feature: Redis-Module 구현
  backend/application-modules/settings.gradle
  backend/infrastructure-modules/redis-module/build.gradle
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisConfiguration.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisProperties.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/BuiltinType.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/RecordMapper.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/Type.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/TypeConverterRegistry.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/TypeUtils.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/scan/RedisDataScanner.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/scan/RedisKeyGenerator.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/scan/RedisKeyScanner.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/BackoffStrategy.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/Bucket4jConfiguration.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ThrottleException.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ThrottleExceptionStatus.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ThrottlingManager.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/ThrottlingProperties.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/RedisKeyGeneratorTest.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/RedisKeyScannerTest.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/RedisTest.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/scan/RedisDataScannerTest.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/throttle/ThrottlingManagerRetryTest.java
  backend/infrastructure-modules/redis-module/src/test/java/com/softeer/throttle/ThrottlingManagerTest.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/RedisContainerContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithRedis.java
  backend/settings.gradle
Labels: ⚙️ Setting, ✨ Feature, ✅ Test

#157 [BE] - ✨ Feature: 산 및 코스 정보 조회 API 구현
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/CourseInfoResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
  backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
Labels: ✨ Feature, ✅ Test

#169 [BE] - 🔧 Chore: CD 로직 수정
  .github/workflows/BE-CD.yml
  backend/application-modules/api-server/src/main/resources/application-prod.yml
  backend/appspec.yml
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisConfiguration.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisProperties.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/RedisContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithRedis.java
  backend/scripts/deploy/before_install.sh
  backend/scripts/deploy/cleanup_s3.sh
  backend/scripts/deploy/manage_images.sh
  backend/scripts/deploy/manage_images_entry.sh
  backend/scripts/deploy/rollback.sh
  backend/scripts/deploy/start_application.sh
  backend/scripts/deploy/stop_application.sh
  backend/scripts/deploy/validate_service.sh
Labels: ⚙️ Setting, 🌎 Deploy

#174 [BE] - 🚀 Release: Redis 설정 추가 배포
  .github/workflows/BE-CD.yml
  backend/application-modules/api-server/src/main/resources/application-prod.yml
  backend/appspec.yml
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisConfiguration.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/RedisProperties.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/RedisContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithContainer.java
  backend/infrastructure-modules/testcontainers-module/src/testFixtures/java/com/softeer/SpringBootTestWithRedis.java
  backend/scripts/deploy/before_install.sh
  backend/scripts/deploy/cleanup_s3.sh
  backend/scripts/deploy/manage_images.sh
  backend/scripts/deploy/manage_images_entry.sh
  backend/scripts/deploy/rollback.sh
  backend/scripts/deploy/start_application.sh
  backend/scripts/deploy/stop_application.sh
  backend/scripts/deploy/validate_service.sh
Labels: 🌎 Deploy

#179 [BE] - 🚀 Release: Batch redis 설정 수정
  backend/application-modules/batch-server/src/main/resources/application-prod.yml
Labels: 🌎 Deploy

#202 [FE] - ✨ Feature: MainPage, ReportPage에 tanstack query 적용
  frontend/src/components/organisms/Common/SearchBar.tsx
  frontend/src/components/organisms/Common/utils.ts
  frontend/src/components/organisms/Report/BackReportCard.tsx
  frontend/src/components/organisms/Report/HeartStat.tsx
  frontend/src/components/organisms/Report/ReportModal.tsx
  frontend/src/components/templates/Main/MainSearchSection.tsx
  frontend/src/components/templates/Main/MountainCardSection.tsx
  frontend/src/components/templates/Main/utils.ts
  frontend/src/components/templates/Report/ReportCardSection.tsx
  frontend/src/components/templates/Report/ReportSearchSection.tsx
  frontend/src/hooks/useApiMutation.ts
  frontend/src/hooks/useApiQuery.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/utils.ts
Labels: ✨ Feature, 📬 API

#200 [BE] - ✨ Feature: 카드 기록 저장 로직 구현
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/CourseScheduleCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/ForecastOverview.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/MountainCourseCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/InteractionCommandCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/WeatherCardController.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/InteractionCommandCardService.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/WeatherCardService.java
  backend/application-modules/api-server/src/test/java/com/softeer/service/WeatherCardServiceTest.java
  backend/common-modules/util/src/main/java/com/softeer/activity/HikingActivityCalculator.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/entity/CardHistoryEntity.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/CardHistoryAdapter.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryAdapterImpl.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryJpaRepository.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/CardHistoryUseCase.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/impl/CardHistoryUseCaseImpl.java
Labels: ✨ Feature

#216 [BE] - ✨ Feature: 사용자 프로필 변경 API 구현
  backend/application-modules/api-server/src/main/java/com/softeer/config/SwaggerConfig.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/request/UpdateNicknameRequest.java
  backend/application-modules/api-server/src/main/java/com/softeer/dto/response/card/CourseScheduleCardResponse.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/UserApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/WeatherCardApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/SignController.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/UserController.java
  backend/application-modules/api-server/src/main/java/com/softeer/service/UserService.java
  backend/application-modules/batch-server/src/main/resources/application-prod.yml
  backend/domain-modules/image-domain/src/main/java/com/softeer/service/ImageUseCase.java
  backend/domain-modules/image-domain/src/main/java/com/softeer/service/ImageUseCaseImpl.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/UserAdapter.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserAdapterImpl.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserJpaRepository.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/ProfileCommandUseCase.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/impl/ProfileCommandUseCaseImpl.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/retry/AsyncRetryHandler.java
  backend/infrastructure-modules/s3-client-module/src/main/java/com/softeer/service/S3Service.java
Labels: ✨ Feature, 🔨 Refactor

#221 [BE] - 💎 Refactor: 날씨 응답 description 데이터 변경
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/PrecipitationType.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/Sky.java
Labels: 🔨 Refactor

#225 [BE] - 🐞 BugFix: 코스아이디 유저아이디 순서 조정
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v1/UltraForecastV1Writer.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/report/impl/ReportQuerydslRepository.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/impl/ReportCommandUseCaseImpl.java
  backend/scripts/deploy/start_application.sh
Labels: 🌎 Deploy, 🐞 BugFix

#226 [BE] - 🚀 Release: 제보 좋아요 오류 수정 반영 배포
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/v1/UltraForecastV1Writer.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/PrecipitationType.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/enums/Sky.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/report/impl/ReportQuerydslRepository.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/service/impl/ReportCommandUseCaseImpl.java
  backend/infrastructure-modules/s3-client-module/src/main/java/com/softeer/service/S3Service.java
  backend/scripts/deploy/start_application.sh
Labels: 🌎 Deploy, 🐞 BugFix

#228 [BE] - 배치 처리 job, step 설정
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/support/BatchNames.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/config/ChainedJobConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/scheduler/ChainedJobScheduler.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/config/MountainForecastJobConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/scheduler/MountainForecastJobScheduler.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/config/ShortForecastJobConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/processor/ShortForecastProcessor.java
Labels: ✨ Feature

#234 [FE] - ✨ Feature: 제보페이지에서의 제보카드들의 무한 스크롤 구현 및 좋아요 낙관적 업데이트
  frontend/src/components/molecules/ReportCard/BackReportCardHeader.tsx
  frontend/src/components/molecules/ReportCard/FrontCardFooter.tsx
  frontend/src/components/organisms/Main/MountainCard.tsx
  frontend/src/components/organisms/Report/BackReportCard.tsx
  frontend/src/components/organisms/Report/BaseModal.tsx
  frontend/src/components/organisms/Report/FrontReportCard.tsx
  frontend/src/components/organisms/Report/HeartStat.tsx
  frontend/src/components/templates/Main/MountainCardSection.tsx
  frontend/src/components/templates/Report/ReportCardSection.tsx
  frontend/src/hooks/useApiInfiniteQuery.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/ReportPage/ReportPage.tsx
Labels: ✨ Feature

#240 [FE] - ✨ Feature : MyPage 상단 내 정보 및 최근 조회 UI 구현
  frontend/src/components/templates/Login/MyPageTemplate.tsx
  frontend/src/components/templates/MyPage/MyInfoSection.tsx
  frontend/src/components/templates/MyPage/RecentClimbSection.tsx
  frontend/src/constants/placeholderData.ts
  frontend/src/pages/LoginPage/LoginPage.tsx
  frontend/src/pages/MyPage/MyPage.tsx
Labels: 🎨 Html&css, 📬 API

#232 [BE] - ✨ Feature: 산악, 단기 예보 api 응답 데이터 Redis 저장
  .github/workflows/BE-CD.yml
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/dto/RedisTtlWrite.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/DailyTemperatureWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/ForecastJdbcWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/writersupporter/SunTimeJdbcWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/context/DailyTemperatureContextAccessor.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/context/ExecutionContextKeys.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/dto/DailyTemperatureKey.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/chained/dto/DailyTemperatureValue.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/config/MountainForecastStepConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/listener/DailyTemperatureLoader.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/AbstractMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/ScheduledMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/StartUpMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/config/ShortForecastStepConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/listener/DailyTemperatureCollector.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/processor/ShortForecastProcessor.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/AbstractShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/ScheduledShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/StartUpShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/AbstractUltraForecastProcessor.java
  backend/application-modules/batch-server/src/main/resources/application-prod.yml
  backend/common-modules/util/src/main/java/com/softeer/time/TimeUtil.java
  backend/domain-modules/forecast-domain/src/main/java/com/softeer/entity/ForecastRedisEntity.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/mapper/RecordMapper.java
Labels: ✨ Feature

#251 [FE] - 🐞 BugFix: MyLikeSection의 쿼리 키 수정 및 ReportCardSection의 필터 필드명 수정
  frontend/src/components/templates/MyPage/MyLikeSection.tsx
  frontend/src/components/templates/Report/ReportCardSection.tsx
Labels: 🐞 BugFix

#253 [BE] - 🐞 BugFix:
  backend/application-modules/api-server/src/main/java/com/softeer/config/WebConfiguration.java
Labels: 🐞 BugFix

#256 [BE] - 🚀 Release: 단기 예보 배치 유량 제어 로직 적용 후 배포
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/UserApi.java
  backend/application-modules/api-server/src/main/java/com/softeer/presentation/impl/UserController.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/common/support/BatchNames.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/config/MountainForecastStepConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/processor/MountainForecastV2Processor.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v1/AbstractMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v1/ScheduledMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v1/StartUpMountainForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v2/AbstractMountainForecastV2Writer.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v2/ScheduledMountainForecastV2Writer.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/writer/v2/StartUpMountainForecastV2Writer.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/config/ShortForecastStepConfig.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/processor/ShortForecastV2Processor.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v1/AbstractShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v1/ScheduledShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v1/StartUpShortForecastWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v2/AbstractShortForecastV2Writer.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v2/ScheduledShortForecastV2Writer.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/writer/v2/StartUpShortForecastV2Writer.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/ProfileCommandUseCase.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/service/impl/ProfileCommandUseCaseImpl.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/AbstractThrottlingManager.java
Labels: 🌎 Deploy

#258 [BE] - ✨ Feature: CORS 허용 도메인 추가
  backend/application-modules/api-server/src/main/java/com/softeer/config/WebConfiguration.java
Labels: ✨ Feature

#263 [BE] - 🐞 BugFix: CardHistory 조회 로직의 검색 조건 누락 문제 해결
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/ultra/UltraForecastJobScheduler.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryAdapterImpl.java
  backend/domain-modules/interaction-domain/src/main/java/com/softeer/repository/history/impl/CardHistoryJpaRepository.java
Labels: 🐞 BugFix

#265 [FE] - ✨ Feature: 예보페이지 로딩창 구현
  frontend/src/components/organisms/Loading/Loading.tsx
  frontend/src/components/templates/Forecast/ForecastSearchSection.tsx
Labels: ✨ Feature

#272 [FE] - 🐞 BugFix: 예보페이지 로딩창 스크롤 버그 수정
  frontend/src/components/organisms/Loading/Loading.tsx
Labels: 🐞 BugFix

#276 [FE] - 🐞 BugFix: selectedWeekdayId변화를 ScrollSelectedTime에 반영
  frontend/src/components/templates/Forecast/DetailInfoSection.tsx
Labels: 🐞 BugFix

#278 [BE] - ✨ Feature:
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
Labels: ✨ Feature

#279 [BE] - 🚀 Release: Redis 데이터 저장 필터링 추가 배포
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
Labels: 🌎 Deploy

#283 [FE] - ✨ Feature : 카드 생성 및 로그인/라우팅 기능 개선 + 로딩/에러 처리 및 UI 리팩토링
  frontend/src/App.tsx
  frontend/src/assets/bg.png
  frontend/src/components/atoms/Button/DownLoadButton.tsx
  frontend/src/components/atoms/Button/ToggleButton.tsx
  frontend/src/components/molecules/Button/LoginRequiredModal.tsx
  frontend/src/components/molecules/Forecast/MountainInfoPreview.tsx
  frontend/src/components/molecules/Header/IconNavList.tsx
  frontend/src/components/organisms/Forecast/WeatherCard.tsx
  frontend/src/components/organisms/Forecast/WeatherCardGroup.tsx
  frontend/src/components/organisms/Forecast/WeatherSummaryCardModal.tsx
  frontend/src/components/organisms/Login/LoginForm.tsx
  frontend/src/components/templates/Forecast/DetailInfoSection.tsx
  frontend/src/components/templates/Forecast/ForecastBackgroundSection.tsx
  frontend/src/components/templates/Forecast/SummaryInfoSection.tsx
  frontend/src/components/templates/Forecast/dummy.ts
  frontend/src/components/templates/MyPage/MyInfoSection.tsx
  frontend/src/components/templates/MyPage/RecentClimbSection.tsx
  frontend/src/components/templates/MyPage/WeatherSummaryCard.tsx
  frontend/src/components/templates/Register/RegisterFormSection.tsx
  frontend/src/hooks/useForecastCardData.ts
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#286 [FE] - ✨ Feature: UX 개선
  frontend/src/components/molecules/Input/ImageInputField.tsx
  frontend/src/components/molecules/Modal/FilterModalContent.tsx
  frontend/src/components/molecules/Modal/LoginRequiredModal.tsx
  frontend/src/components/molecules/Modal/ReportModalContent.tsx
  frontend/src/components/organisms/Common/Header.tsx
  frontend/src/components/organisms/Forecast/WeatherSummaryCardModal.tsx
  frontend/src/components/organisms/Loading/Loading.tsx
  frontend/src/components/organisms/Main/MountainCard.tsx
  frontend/src/components/organisms/Report/FilterModal.tsx
  frontend/src/components/organisms/Report/LabelButtonsColumn.tsx
  frontend/src/components/organisms/Report/ReportCardWrapper.tsx
  frontend/src/components/organisms/Report/ReportModal.tsx
  frontend/src/components/templates/Alert/AlertSearchSection.tsx
  frontend/src/components/templates/Forecast/ForecastSearchSection.tsx
  frontend/src/components/templates/Main/MainSearchSection.tsx
  frontend/src/components/templates/MyPage/MyInfoSection.tsx
  frontend/src/components/templates/MyPage/MyLikeSection.tsx
  frontend/src/components/templates/MyPage/MyReportSection.tsx
  frontend/src/components/templates/Report/ReportCardSection.tsx
  frontend/src/components/templates/Report/ReportSearchSection.tsx
  frontend/src/components/templates/Report/utils.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/pages/ReportPage/ReportPage.tsx
  frontend/src/types/filterTypes.d.ts
  frontend/src/types/reportCardTypes.d.ts
  frontend/src/types/searchBarTypes.d.ts
  frontend/src/utils/utils.ts
Labels: ✨ Feature, 🐞 BugFix

#285 [BE] - 🚀 Release: 사진 요청 최대 크기 조정 후 배포
  backend/application-modules/api-server/src/main/resources/application-prod.yml
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/mountain/redis/MountainForecastRedisWriter.java
  backend/application-modules/batch-server/src/main/java/com/softeer/batch/forecast/shortterm/redis/ShortForecastRedisWriter.java
  backend/infrastructure-modules/redis-module/src/main/java/com/softeer/throttle/manager/AbstractThrottlingManager.java
Labels: 🌎 Deploy

#290 [BE] - 🚀 Release: 회원가입 시 default image 삽입 적용 후 배포
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserAdapterImpl.java
  backend/domain-modules/user-domain/src/main/java/com/softeer/repository/impl/UserJpaRepository.java
Labels: 🌎 Deploy
