Repository softeerbootcamp-6th/Team6-6CanDoIt, pull requests merged in 2025-07, with the labels that each got.

#3 ISSUE_TEMPLATE 설정
  .github/ISSUE_TEMPLATE/✔-feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/💎-refactor.md
  .github/ISSUE_TEMPLATE/📚-documents.md
Labels: documentation

#8 💎 Refactor: properties -> yml 이름 변경
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: ⚙️ Setting, 🔨 Refactor

#10 ✨ Feature : 아이콘 생성 컴포넌트
  .gitignore
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/atoms/Icons.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: ✨ Feature

#11 🎨 Art : 전역 CSS속성 및 폰트 설정, sass 설치
  .gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/styles/colors.scss
  frontend/src/styles/fonts.scss
  frontend/src/styles/main.scss
  frontend/src/styles/reset.css
  frontend/src/styles/typography.scss
Labels: ✨ Feature
